solvers:
  - name: "PYTHON-Sudoku._solve_bruteforce"
    command: "python3 solvers/sudokusolver.py"

  - name: "PYTHON-Sudoku._solve_bruteforce_v2"
    command: "python3 solvers/sudokusolver.py"

  - name: "PYTHON-phbeck-sudokuSolver"
    command: "python3 solvers/phbeck/main.py"
  
  - name: "C-bruteforcer.c"
    build: "gcc -O3 solvers/bruteforcer.c -o solvers/bruteforcer"
    command: "./solvers/bruteforcer"

sudokus:
  - easy: "data/sudoku0.txt"
  - easy: "data/sudoku1.txt"
  - medium: "data/sudoku2.txt"
  - medium: "data/sudoku3.txt"